brew "antidote"
brew "ccusage"
brew "fileicon"
brew "golangci-lint"
brew "mise"
brew "ncurses"
brew "neovim"
brew "rcm"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "tmux"
brew "tree-sitter-cli"

cask "font-jetbrains-mono-nerd-font"
cask "kitty"
