#!/bin/sh

reset -Q

################################################################################
# Tmux package manager
################################################################################
TPMPath="$HOME/.tmux/plugins/tpm"
if [ ! -d "$TPMPath" ]; then
  echo "TPM not found. Installing..."
  git clone https://github.com/tmux-plugins/tpm "$TPMPath"
else
  echo "TPM is already installed."
fi

################################################################################
# Homebrew requirements
################################################################################
HomebrewTaps=(
 "homebrew/cask-fonts"
)

for Tap in "${HomebrewTaps[@]}"; do
  brew tap $Tap
done

HomebrewFormulas=(
  "antigen"
  "asdf"
  "golangci-lint"
  "ncurses"
  "neovim"
  "tmux"
  "reattach-to-user-namespace"
  "ripgrep"
)
for Formula in "${HomebrewFormulas[@]}"; do
  if [ `which $Formula | grep -c "not found"` -eq 0 ]; then
    brew install $Formula
  else
    brew upgrade $Formula
  fi
done

HomebrewCasks=(
  "font-jetbrains-mono-nerd-font"
  "kitty"
)
for Cask in "${HomebrewCasks[@]}"; do
  if [ `which $Cask | grep -c "not found"` -eq 0 ]; then
    brew install --cask $Cask
  else
    brew upgrade --cask $Cask
  fi
done

################################################################################
# Copy tool versions for ASDF to use
################################################################################
echo "Overwriting .tool-versions"
cp ~/dotfiles/tool-versions ~/.tool-versions

################################################################################
# Install ASDF plugins and tool versions
################################################################################
echo "Add ASDF plugins and install tool versions"
asdf plugin add golang https://github.com/asdf-community/asdf-golang.git
asdf plugin-add java https://github.com/halcyon/asdf-java.git
asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf plugin-add python
asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
asdf plugin update --all
asdf install

################################################################################
# Global NPM packages
################################################################################
GlobalNodeModules=(
  "npm"
  # "bash-language-server"
  # "typescript"
  # "typescript-language-server"
  # "vscode-langservers-extracted"
)
for NodeModule in "${GlobalNodeModules[@]}"; do
  if [ `npm list -g | grep -c $NodeModule` -eq 0 ]; then
    npm install -g $NodeModule
  fi
done

################################################################################
# Ruby gems
################################################################################
Gems=(
  # "solargraph"
)
for Gem in "${Gems[@]}"; do
  if [ `gem list $Gem | grep -c $Gem` -eq 0 ]; then
    gem install $Gem
  fi
done
